---
AbcMetricMethodCheck:            { score: 24.2 }
#AssignmentInConditionalCheck:    { }
CaseMissingElseCheck:            { }
ClassLineCountCheck:             { line_count: 235 }
#ClassNameCheck:                  { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
ClassVariableCheck:              { }
CyclomaticComplexityBlockCheck:  { complexity: 4 }
CyclomaticComplexityMethodCheck: { complexity: 10 }
EmptyRescueBodyCheck:            { }
ForLoopCheck:                    { }
# TODO: decrease line_count to 5 to 10
MethodLineCountCheck:            { line_count: 144 }
#MethodNameCheck:                 { pattern: !ruby/regexp /\A(?:[a-z](?:_?[a-z])+[?!]?|\[\]=?|==|<=>|[+*&|-])\z/ }
ModuleLineCountCheck:            { line_count: 237 }
#ModuleNameCheck:                 { pattern: !ruby/regexp /\A[A-Z][a-z](?:[A-Z]?[a-z])+\z/ }
# TODO: decrease parameter_count to 2 or less
ParameterNumberCheck:            { parameter_count: 3 }
